// Short the alphabets
export const Truncate = (str,n) =>{
    return str?.length > n ? str.substr(0, n - 1) + '...' : str;
}

// OurProducts items
export  const Electronics = [
    {
        "id":1,
        "brand":"Sony",
        "prodName":"jony XB10 Portable  Wireless Speaker",
        "price":30.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-1.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-2.jpg",
        "latest" : true,
        "sale" : 10,
        "special":true,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
        "ratings":["great","Fantastic","very useful","TrustWorthy"],
        "description":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.",
        "isStock":true,
        "colors":['']
    },
    {
        "id":2,
        "brand":"Microsoft",
        "prodName":"Windows 10 - Product of Microsoft",
        "price":10.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-3.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-4.jpg",
        "latest" : true,
        "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],

    },
    {
        "id":3,
        "brand":"Gucci",
        "prodName":"Reck Sneakers - Gucci A American Brand",
        "price":7.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-5.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-6.jpg",
        "latest" : false,
        "shots":["https://uparzon.com.bd/assets/img/product/product-7.jpg","https://uparzon.com.bd/assets/img/product/product-8.jpg","https://uparzon.com.bd/assets/img/product/product-9.jpg","https://uparzon.com.bd/assets/img/product/product-10.jpg","https://uparzon.com.bd/assets/img/product/product-11.jpg","https://uparzon.com.bd/assets/img/product/product-12.jpg"],
    },
    {
        "id":4,
        "brand":"Nike",
        "prodName":"Portable Back Pack - Nike Just Do It",
        "price":22.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-7.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-8.jpg",
        "latest" : false,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":5,
        "brand":"Lotto",
        "prodName":"Jungle Tees - Lotto Italian brand",
        "price":9.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-10.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-9.jpg",
        "latest" : false,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":6,
        "brand":"Tommy Hillfiger",
        "prodName":"Water Ressist Sporty Watch - Tommy Hillfiger",
        "price":66.3,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-11.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-12.jpg",
        "latest" : false,
        "sale" : 20,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":7,
        "brand":"Allen Solly",
        "prodName":"Underuniverse Trouser - Allen Solly AUS",
        "price":75.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-13.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-14.jpg",
        "latest" : false,
        "sale" : 30,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
]
// Audio Home theatre items
export  const Entertainments = [
    {
        "id":8,
        "brand":"Sony",
        "prodName":"Sony MS5500 5.1 Channel Speakers Black",
        "price":124.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-1.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-2.jpg",
        "latest" : true,
        "sale" : 7,
        "special":true,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":9,
        "brand":"Croma",
        "prodName":"Croma CRES1082 5.1 Channel Speaker Vlack",
        "price":150.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-3.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-4.jpg",
        "latest" : true,
        "sale" : 5,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":10,
        "brand":"Sony",
        "prodName":"Sony BDV-E4100 5.1 Home Theatre System",
        "price":227.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-5.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-6.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":11,
        "brand":"Phillips",
        "prodName":"Philips SPA3000U 5.1 Speakers",
        "price":422.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-7.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-8.jpg",
        "latest" : false,
        "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":12,
        "brand":"Payoneer",
        "prodName":"Pioneer VSX-323K and SPE335XT 5.1 Component Home Theatre System",
        "price":449.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-10.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-9.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":13,
        "brand":"Zebronic",
        "prodName":"Zebronic SPK-SWT8290 5.1 Speaker System",
        "price":366.3,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-11.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-12.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":14,
        "brand":"JBL",
        "prodName":"JBL Cinema BD 100 Complete 5.1-Channel 3D Blu-ray Disc Integrated Home Theater System",
        "price":475.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-13.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-14.jpg",
        "latest" : false,
        "sale" : 44,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
]
// Cellphones & Accessories items
export  const MobileProducts = [
    {
        "id":15,
        "brand":"Oppo",
        "prodName":"Oppo K7x - Latest Phone in 2020",
        "price":124.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-1.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-2.jpg",
        "latest" : true,
        "sale" : 5,
        "special":true,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":16,
        "brand":"Infinix",
        "prodName":"Infinix Smart 4",
        "price":150.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-3.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-4.jpg",
        "latest" : true,
        "sale" : 8,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":17,
        "brand":"Sony",
        "prodName":"Sony Experia",
        "price":227.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-5.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-6.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":18,
        "brand":"OnePlus",
        "prodName":"OnePlus 8T Cyberpunk 2077 Limited Edition",
        "price":422.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-7.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-8.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":19,
        "brand":"ZTE",
        "prodName":"ZTE Blade A3Y (Yahoo Mobile)",
        "price":449.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-10.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-9.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":20,
        "brand":"Huawei",
        "prodName":"Huawei Mate 40 Pro",
        "price":366.3,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-11.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-12.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":21,
        "brand":"Gionee",
        "prodName":"Gionee F8 Neo",
        "price":475.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-13.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-14.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
]

//654654687489746546476846476496476464647464647646

export const quickViewprod = [
    {
        "id":1,
        "brand":"Sony",
        "prodName":"jony XB10 Portable  Wireless Speaker",
        "price":30.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-1.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-2.jpg",
        "latest" : true,
        "sale" : 10,
        "special":true,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":2,
        "brand":"Microsoft",
        "prodName":"Windows 10 - Product of Microsoft",
        "price":10.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-3.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-4.jpg",
        "latest" : true,
        "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],

    },
    {
        "id":3,
        "brand":"Gucci",
        "prodName":"Reck Sneakers - Gucci A American Brand",
        "price":7.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-5.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-6.jpg",
        "latest" : false,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":4,
        "brand":"Nike",
        "prodName":"Portable Back Pack - Nike Just Do It",
        "price":22.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-7.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-8.jpg",
        "latest" : false,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":5,
        "brand":"Lotto",
        "prodName":"Jungle Tees - Lotto Italian brand",
        "price":9.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-10.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-9.jpg",
        "latest" : false,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":6,
        "brand":"Tommy Hillfiger",
        "prodName":"Water Ressist Sporty Watch - Tommy Hillfiger",
        "price":66.3,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-11.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-12.jpg",
        "latest" : false,
        "sale" : 20,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":7,
        "brand":"Allen Solly",
        "prodName":"Underuniverse Trouser - Allen Solly AUS",
        "price":75.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-13.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-14.jpg",
        "latest" : false,
        "sale" : 30,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":8,
        "brand":"Sony",
        "prodName":"Sony MS5500 5.1 Channel Speakers Black",
        "price":124.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-1.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-2.jpg",
        "latest" : true,
        "sale" : 7,
        "special":true,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":9,
        "brand":"Croma",
        "prodName":"Croma CRES1082 5.1 Channel Speaker Vlack",
        "price":150.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-3.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-4.jpg",
        "latest" : true,
        "sale" : 5,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":10,
        "brand":"Sony",
        "prodName":"Sony BDV-E4100 5.1 Home Theatre System",
        "price":227.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-5.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-6.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":11,
        "brand":"Phillips",
        "prodName":"Philips SPA3000U 5.1 Speakers",
        "price":422.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-7.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-8.jpg",
        "latest" : false,
        "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":12,
        "brand":"Payoneer",
        "prodName":"Pioneer VSX-323K and SPE335XT 5.1 Component Home Theatre System",
        "price":449.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-10.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-9.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":13,
        "brand":"Zebronic",
        "prodName":"Zebronic SPK-SWT8290 5.1 Speaker System",
        "price":366.3,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-11.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-12.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":14,
        "brand":"JBL",
        "prodName":"JBL Cinema BD 100 Complete 5.1-Channel 3D Blu-ray Disc Integrated Home Theater System",
        "price":475.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-13.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-14.jpg",
        "latest" : false,
        "sale" : 44,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":15,
        "brand":"Oppo",
        "prodName":"Oppo K7x - Latest Phone in 2020",
        "price":124.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-1.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-2.jpg",
        "latest" : true,
        "sale" : 5,
        "special":true,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":16,
        "brand":"Infinix",
        "prodName":"Infinix Smart 4",
        "price":150.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-3.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-4.jpg",
        "latest" : true,
        "sale" : 8,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":17,
        "brand":"Sony",
        "prodName":"Sony Experia",
        "price":227.31,
        // "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-5.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-6.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":18,
        "brand":"OnePlus",
        "prodName":"OnePlus 8T Cyberpunk 2077 Limited Edition",
        "price":422.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-7.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-8.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":19,
        "brand":"ZTE",
        "prodName":"ZTE Blade A3Y (Yahoo Mobile)",
        "price":449.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-10.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-9.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":20,
        "brand":"Huawei",
        "prodName":"Huawei Mate 40 Pro",
        "price":366.3,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-11.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-12.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },
    {
        "id":21,
        "brand":"Gionee",
        "prodName":"Gionee F8 Neo",
        "price":475.31,
        "oldPrice":466.0,
        "img1":"https://uparzon.com.bd/assets/img/product/product-13.jpg",
        "img2":"https://uparzon.com.bd/assets/img/product/product-14.jpg",
        "latest" : false,
        // "sale" : 12,
        "shots":["https://uparzon.com.bd/assets/img/product/product-1.jpg","https://uparzon.com.bd/assets/img/product/product-2.jpg","https://uparzon.com.bd/assets/img/product/product-3.jpg","https://uparzon.com.bd/assets/img/product/product-4.jpg","https://uparzon.com.bd/assets/img/product/product-5.jpg","https://uparzon.com.bd/assets/img/product/product-6.jpg"],
    },    
] 